services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: goboard
        image: server
        restart: unless-stopped
        env_file: .env
        ports:
            - "$APP_PORT:$APP_PORT"
        depends_on:
            - mysql
        networks:
            - server

    mysql:
        container_name: mysql
        image: mysql:8.0
        restart: unless-stopped
        env_file: .env
        ports:
            - "$DB_PORT:$DB_PORT"
        environment:
            MYSQL_ROOT_PASSWORD: "$DB_PASS"
            MYSQL_DATABASE: "$DB_SCHEMA"
            TZ: "Asia/Seoul"
        networks:
            - server

networks:
    server:
        driver: bridge
